# docker-compose.override.yml
# "Home production" hardening without overkill: resources, restart, logging, auth envs.

services:
  agent-gateway:
    env_file: [.env]
    environment:
      GATEWAY_API_KEY: "${GATEWAY_API_KEY}"
      KG_API_URL: "http://kg-api:8000"

    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: 1g
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "3"
    ulimits:
      nofile: 65535
    restart: unless-stopped

  kg-api:
    env_file: [.env]
    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: 1g
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "3"
    restart: unless-stopped

  neo4j:
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "3"

  postgres:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "3"
  neo4j-init:
    image: neo4j:5-community
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      NEO4J_PASSWORD: "${NEO4J_PASSWORD:-neo4j_password}"
    volumes:
      - ./init/neo4j:/init:ro
    entrypoint: >
      bash -lc "cypher-shell -a bolt://neo4j:7687 -u neo4j -p ${NEO4J_PASSWORD}
      -f /init/constraints.cypher && echo 'neo4j constraints applied'"
    restart: "no"
